// Generated by CoffeeScript 1.3.3
(function() {

  $.widget("stults.primeGame", {
    options: {
      size: 5,
      hexBuilder: new HexBuilder(50, 1.15, [150, 100]),
      elementId: "primeGame",
      goalValue: 77,
      svg: null
    },
    _setOption: function(key, value) {
      if (key === 'size') {
        value = this._constrainSize(value);
      }
      if (key === 'hexBuilder') {
        this.isBuilt = false;
      }
      return this._super(key, value);
    },
    _setOptions: function(options) {
      this._super(options);
      return this.refresh();
    },
    _constrainSize: function(size) {
      if (size < 1) {
        return 1;
      }
      return size;
    },
    refresh: function() {
      if (!(this.options.svg != null)) {
        this.options.svg = this.element.svg('get');
      }
      if ((this.goal != null) && this.options.goalValue !== this.goal.boxLine("option", "value")) {
        return this.goal.boxLine("option", "value", this.options.goalValue);
      }
    },
    _create: function() {
      var that;
      this.element.addClass("primeGame");
      if (!(this.options.svg != null)) {
        this.element.svg();
      }
      that = this;
      this.goal = $("<div></div>").appendTo(this.element).boxLine({
        elementId: this.options.elementId + "Goal",
        svg: this.options.svg,
        xPos: 375,
        size: this.options.size * 2,
        value: this.options.goalValue,
        hexBuilder: this.options.hexBuilder
      });
      this.result = $("<div></div>").appendTo(this.element).boxLine({
        elementId: this.options.elementId + "Result",
        svg: this.options.svg,
        xPos: 325,
        size: this.options.size * 2,
        value: 0,
        hexBuilder: this.options.hexBuilder
      });
      this.grid = $("<div></div>").appendTo(this.element).hexGrid({
        elementId: this.options.elementId + "Board",
        svg: this.options.svg,
        hexBuilder: this.options.hexBuilder,
        update: function(event, data) {
          return that.result.boxLine("option", "value", data.value);
        }
      });
      this.rhs = $("<div></div>").appendTo(this.element).hexLine({
        elementId: this.options.elementId + "Rhs",
        svg: this.options.svg,
        hexBuilder: this.options.hexBuilder,
        axis: 'y',
        update: function(event, data) {
          return that.grid.hexGrid("option", "rhs", data.value);
        }
      });
      this.lhs = $("<div></div>").appendTo(this.element).hexLine({
        elementId: this.options.elementId + "Lhs",
        svg: this.options.svg,
        hexBuilder: this.options.hexBuilder,
        axis: 'x',
        update: function(event, data) {
          return that.grid.hexGrid("option", "lhs", data.value);
        }
      });
      return this.refresh();
    }
  });

}).call(this);
