// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.util = (function() {

    function util() {}

    util.getURLParm = function(param, def) {
      var matches;
      matches = location.search.match([param, '=(.+?)(&|$)'].join(''));
      if (matches != null) {
        return matches[1];
      } else {
        return def;
      }
    };

    util.drawTextAtPoint = function(svg, parent, pos, text) {
      var bound;
      text = svg.text(parent, text);
      bound = text.getBBox();
      return $(text).attr("x", pos[0] - bound.width / 2).attr("y", pos[1] + bound.height / 4);
    };

    return util;

  })();

}).call(this);
