// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.util = (function() {

    function util() {}

    util.getURLParm = function(param, def) {
      var matches;
      matches = location.search.match([param, '=(.+?)(&|$)'].join(''));
      if (matches != null) {
        return matches[1];
      } else {
        return def;
      }
    };

    return util;

  })();

}).call(this);
